#define BIG_YO 0xA2 // Ё
#define SMALL_YO 0xB5 // ё

char Char_Table[] = {
    'A',    // A
    0xA0,   // Б
    'B',    // В
    0xA1,   // Г
    0xE0,   // Д
    'E',    // Е
    0xA3,   // Ж
    0xA4,   // З
    0xA5,   // И
    0xA6,   // Й
    'K',    // К
    0xA7,   // Л
    'M',    // M
    'H',    // Н
    'O',    // О
    0xA8,   // П
    'P',    // Р
    'C',    // С
    'T',    // Т
    0xA9,   // У
    0xAA,   // Ф
    'X',    // Х
    0xE1,   // Ц
    0xAB,   // Ч
    0xAC,   // Ш
    0xE2,   // Щ
    0xAD,   // Ъ
    0xAE,   // Ы
    'b',    // Ь
    0xAF,   // Э
    0xB0,   // Ю
    0xB1,   // Я
    'a',    // а
    0xB2,   // б
    0xB3,   // в
    0xB4,   // г
    0xE3,   // д
    'e',    // е
    0xB6,   // ж
    0xB7,   // з
    0xB8,   // и
    0xB9,   // й
    0xBA,   // к
    0xBB,   // л
    0xBC,   // м
    0xBD,   // н
    'o',    // о
    0xBE,   // п
    'p',    // р
    'c',    // с
    0xBF,   // т
    'y',    // у
    0xE4,   // ф
    'x',    // х
    0xE5,   // ц
    0xC0,   // ч
    0xC1,   // ш
    0xE6,   // щ
    0xC2,   // ъ
    0xC3,   // ы
    0xC4,   // ь
    0xC5,   // э
    0xC6,   // ю
    0xC7,   // я
    SMALL_YO}; // ё
                        
